---

title: "`cre` Simplifying the Application of Correlated Random Effects"
format:
  pdf:
    documentclass: article
author:
    - name: "Fernando Rios-Avila"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
    - name: "Aashima Sinha"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
date: today
abstract: |
  This paper introduces the `cre` command, a prefix type command, that helps in the implementation of Correlated Random Effects (CRE) estimator for linear and nonlinear models. For the linear case, CRE models offer a simple approach that combines the advantages of both fixed effects and random effects estimators, providing consistent estimates identical to the Fixed Effect estimator, but allowing for the identification of coefficients for time-invariant variables. For the nonlinear case, it provides an alternative to fixed effects estimators that may be difficult to implement or simply non-existent. The `cre` command provides a user-friendly approach for estimating these models, supporting both balanced and unbalanced panels, which can be applied to most linear and nonlinear estimators. 

keywords: "Mundlak approach, correlated random effects, panel data "

bibliography:
  - references.bib
---

# Introduction

 Panel data analysis has become increasingly important in empirical research in economics and social sciences, allowing researchers to control for unobserved individual heterogeneity that is believed to be fixed across time. The two main approaches that have been used to model relationships using this type of data have been fixed effects (FE) and random effects (RE) models. Each one of them, however, comes with limitations. One the one hand, while fixed effects models can be used to provide concistent estimates, while controlling for time-invariant unobserved factors, they cannot be used to estimate the effects of time-invariant variables, which is may be relevant for some research questions. On the other hand, while random effects models allows you to identify effects of time invariant variables, the estimation relies on the strong assumptions that individual-specific effects are uncorrelated with other explanatory variables in the model, which is often violated in practice [@wooldridge2019]. 

 While less commonly used, there is a third option that shares some of the strengths of both FE and RE models: Correlated Random Effects (CRE) models. First introduced by @mundlak1978pooling and further developed by @chamberlain1982multivariate, CRE proposes a middle ground approach that to address the limitations of RE models by explicitly allowing for correlation between the individual-specific effects and the time-varying explanatory variables. By doing so, CRE can estimate the effects of time-invariant variables while also provide consistent estimates for time variant coefficients that are identical to the FE estimator in linear models. Despite these advantages, CRE models have seen limited use in applied research, partly due to the lack of readily available software implementations. ^[StataNow released an option for the estimation of CRE models as part of the panel data estimators in June 25, 2024. There are also the community-contributed commands `xthybrid`[@schunck2017], `mundlak`[@perales2013] ] 

 This paper introduces the `cre` command for Stata, which aims to provide a straightforward and flexible tool for estimating CRE models for linear and non-linear models, supporting both balanced and unbalanced panels, as well as multiple fixed effects. This command is a prefix command that identifies all explanatory variables in a model, calculates the group means (or mean-like statistics) for each variable, and adds them to the model to provide a @mundlak1978pooling type estimator. Because of this, there are few restrictions on the type of models that can be estimated using this command, making it a versatile tool for applied researchers. Furthermore, because it integrates seamlessly with Stata's existing estimation commands, all post-estimation commands and diagnostics can be used. 

 We begin in @sec-2 reviewing the theoretical foundations of CRE models and their relationship to FE and RE models, extending our discussion to Multiple fixed effects, and application with non-linear models. @sec-3 present the implementation of CRE estimation in Stata, describing the syntax of the command. Finally, @sec-4 presents a small Monte Carlo simulation to assess the performance of CRE approach. @sec-5 concludes. 

 # Theoretical Framework {#sec-2}

 ## Correlated Random Effects Models - 1 Dimension

 The Correlated Random Effects (CRE) is an alternative estimation approach for panel data models that was first introduced by @mundlak1978pooling and further developed by @chamberlain1982multivariate. In contrast with standard Fixed Effects estimator, CRE allows users to control and identify the effects of time-variant and time-invairant variables. And, in contrast with standard random effects estamator, CRE lifts the assumption that individual-specific effects are uncorrelated with other explanatory variables in the model. As pointed out in @wooldridge2010econometric, for the case of linear models, the CRE point estimates are identical to the Fixed Effects estimator. 

 To understand how CRE models work, let's consider the following data generating process: 

 $$y_{i,t} = \beta_0 + x_{i,t}\beta_x + z_{i}\beta_z  + \alpha_i + u_{i,t}
$${#eq-cre-1}

 where $y_{i,t}$ is the dependent variable for individual $i$ at time $t$, $x_{i,t}$ is a vector of time-varying explanatory variables, $z_i$ a set of time invariant factors, $\alpha_i$ is the individual-specific effect, and $u_{i,t}$ is the idiosyncratic error term.  

 Under the assumption that $\alpha_i$ is uncorrelated with $x_{i,t}$, in addition to the standard assumption of exogeneity of $u_it$, @eq-cre-1 could be consitently estimated using ordinarity least squares (OLS), Random effects estimator, or fixed effects estimator.  

 In the case of using OLS, standard errors would need to be adjusted to account for the fact that $\alpha_i$ is an effect that is clustered within invidivuals. In the case of Fixed effects, if the panel data is balanced, one could simply demean all the variables with group individual means and estimate the model with the transformed data. This demeaning process would eliminate the individual-specific effect $\alpha_i$ from the model, but would also make it impossible to estimate the effects of time-invariant variables. In the case of random effects, one could quasi-demean the data, before estimating the model. This transformation eliminates the within individual autocorrelation, allowing for the estimation coefficients of time-invariant variables. However, this approach is not consistent if the assumption that $\alpha_i$ is uncorrelated with $x_{i,t}$ is violated. 

 The solution proposed by @mundlak1978pooling and @chamberlain1982multivariate was to explicitly allow for correlation between the individual-specific effects and the time-varying explanatory variables, by assuming that the individual-specific effect can expressed as a projection of (mean) time-varying variables plus an uncorrelated disturbance. Specifically: 

 $$\begin{aligned}
Mundlak:  & & \alpha_i &= \gamma_0 + \bar x_{i}\gamma + v_i &  \\
Chamberlain: & & \alpha_i &= \gamma_0 + x_{i,1}\gamma_1 + x_{i,2}\gamma_2 + \dots + x_{i,T}\gamma_T + v_i 
\end{aligned}
$${#eq-cre-2}

 where $\bar x_{i}$ is the individual specific mean of the time-varying variables, $x_{i,t}$ is the realization of $x$ for individual $i$ at time $t$, and $v_i$ is an uncorrelated disturbance. The main difference between both approaches was that @chamberlain1982multivariate allowed for a more flexible specification of the correlation between the individual-specific effect and the time-varying variables. @mundlak1978pooling, on the other hand, assumed that the correlation was constant, only depending on the  individual average. If we substitute @eq-cre-2 into @eq-cre-1, the final model can be written as:  

 $$y_{i,t} = \beta_0 +x_{i,t}\beta_x + z_{i}\beta_z + \gamma_0 + f(x_{i,t})\Gamma + v_i + u_{i,t}
$${#eq-cre-final}

 where $f(x_{i,t})$ can be the full set of time-varying variables or just the average of them. Notice that in this specification, $\beta_0$ and $\gamma_0$ cannot be independently identified, and that the new model now has a compound error $v_i + u_{i,t}=\mu_{i,t}$, which is uncorrelated with $x_{i,t}$ by construction.  

 While this model could now be estimated using OLS, to account for the within-individual correlation driven by $v_i$, the model should be estimated using either random effects estimator, or clustering standard errors at the individual level (see @wooldridge2010econometric for a discussion). Interestingly, both methods provide the same results for time varying covariates if the panel data is balanced, and all covariates are strictly exogenous.^[For time invarying covariates, the RE estimator will be identical to @chamberlain1982multivariate approach only] However, this identity breaks down in other cases (see @abrevaya2013).  

 While both approaches will produce consistent estimates for the time-varying covariates, the implementation of @chamberlain1982multivariate is more difficult when the panel data is unbalanced (see @abrevaya2013). On the other hand, @mundlak1978pooling approach is easier to implement with unbalanced panels, because it only requires the calculation of the individual means for the observed data for each individual, as it has been shown by @wooldridge2019. Furthermore, @mundlak1978pooling only requires adding only few covariates to the model regardless of the number of periods in the panel, compared to an increasing number of covariates in @chamberlain1982multivariate approach. 

 ## Correlated Random Effects Models - Multiple Dimensions

 One potential advantage of CRE-Mundlak estimation that has been less dicussed in the literature is that it can be easily extended to accomodate for multiple fixed effects/dimensions. In the standard case of panel data, for example, one may be interested in controlling for both individual and time fixed effects. Among the few papers discussing this extension, @baltagi2023 focuses on formalizing the equivalence with two-way fixed effect estimation, while @wooldridge2021 have discussed the advantages of CRE-Mundlak estimation for the identification of treatment effects in setups of staggered adoption of treatments. Both authors discuss the CRE-Mundlak approach in the context of two fixed effects, however, the extension to more than two fixed effects is straightforward. 

 Consider the following data generating process: 

 $$y_{i,t} = \beta_0 + x_{i,t}\beta_x + z_{i}\beta_z + w_{t}\beta_w + \alpha_i + \tau_t + u_{i,t}
$${#eq-mcre-1}

 In addition to the components from @eq-cre-1, @eq-mcre-1 also considers individual-invariant variables $w_{t}$, as well as effects that only vary across time, but not individuals $\tau_t$. As before, pool OLS or random effects estimators are only consistent if the individual-specific ($\alpha_i$) and time-specific ($\tau_i$) effects are uncorrelated with the explanatory variables. Without loss of generality let's assume that all variables have an overall mean of zero.  

 Extending the analogy from @eq-cre-2, we can project the sum of individual-specific and time-specif effect as a function of the individual and time averages of $X's$. Other variables are not included because they already are invariant in one of the dimensions: 

 $$
\alpha_i + \alpha_t  = \gamma_0 + \check x_{i}\gamma + \check x_{t}\delta + v_{i,t}
$${#eq-mcre-2}